#!/usr/bin/env bash
# Bash script that configures a new Ubuntu machine
# it Install nginx on on server web-01
# When querying Nginx at its root / with a GET request (requesting a page) using curl, it must return a page that contains the string Hello World!
# can’t use systemctl for restarting nginx


sudo apt-get -y update
sudo apt-get install -y nginx

# Ensure nginx is listening to port 80
ufw allow 'Nginx HTTP'

# Set up the default page
echo "Hello World!" > /var/www/html/index.html

# Restart nginx (without using systemctl)
sudo service nginx restart
