#!/usr/bin/env bash

# Install Nginx
sudo apt update
sudo apt install -y nginx

# Create index.html with "Hello World!"
echo "Hello World!" | sudo tee /var/www/html/index.html

# Configure Nginx for redirection
sudo sed -i '33i\\tlocation /redirect_me {\n\t\trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;\n\t}\n' /etc/nginx/sites-enabled/default

# Check Nginx configuration syntax
if nginx -t; then
    # Restart Nginx if configuration syntax is correct
    sudo service nginx restart
else
    echo "Nginx configuration syntax check failed. Exiting..."
    exit 1
fi
