#!/usr/bin/env bash
# Configure web-02 to be identical with web-01
# an ubuntu machine to have a custom header X-Served-By

sudo apt-get -y update
sudo apt-get -y install nginx

echo "Hello World!" | sudo tee /var/www/html/index.html
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

new_config="add_header X-Served-By \$HOSTNAME;\n\nerror_page 404 /custom_404.html;\nlocation = /custom_404.html {\n\tinternal;\n}\n"

sudo sed -i "s/add_header X-Served-By [^;]*;/${new_config}/" /etc/nginx/nginx.conf

sudo service nginx restart
