#!/usr/bin/env bash
# A Bash script that displays numbers from 1 to 100


for (( loop=1; loop<=100; loop++))
do
	if (( (loop%3 == 0) && (loop%5 == 0) ))
	then
		echo "FizzBuzz"
	elif (( loop%3 == 0 ))
	then
		echo "Fizz"
	elif (( loop%5 == 0 ))
	then
		echo "Buzz"
	else
		echo "$loop"
	fi
done
