#!/usr/bin/env bash
# This script displays the content of the current directory in list format

my_file="/etc/passwd"
while IFS= read -r line
do
    echo "$line" | cut -d":" -f1,3,6
done < "$my_file"
