#!/usr/bin/env bash
# A Bash script that displays "Best School" 10 times using while loop and if statement


loop=1

while [ $loop -le 10 ]
do
    echo "Best School"
    if [ $loop -eq 9 ]
    then
        echo "Hi"
    fi
    ((loop++))
done
