#!/usr/bin/env bash
# A Bash script that displays numbers from 1 to 20

loop=1

while [ $loop -le 20 ]
do
	echo "$loop"
	case $loop in
	"4") echo "bad luck from China";;
	"9") echo "bad luck from Japan";;
	"17") echo "bad luck from Italy";;
	esac
	((loop++))
done
