#!/usr/bin/env bash 
# A script that configures an Ubuntu server with the below requirements
# facebook.com resolves to 8.8.8.8.#!/usr/bin/env bash
# Firstly  makes a copy of original hosts file


sudo cp /etc/hosts ~/hosts.new
# Change localhost resolution by modifying a copy of file
sudo sed -i 's/127.0.0.1.*/127.0.0.2 localhost/' ~/hosts.new

# This is now to add an entry for facebook.com resolving to 8.8.8.8 in the copy of hosts file
echo "8.8.8.8                facebook.com" >> ~/hosts.new

# Overwrite the original hosts file with the modified copy
sudo cp -f ~/hosts.new /etc/hosts
  
# Now remove temporary file and clear DNS cache
rm ~/hosts.new
 sudo /etc/init.d/networking restart > /dev/null
