#!/usr/bin/env bash

# A Script that creates an RSA key pair.
# Name of the created private key must be school
# Number of bits in the created key to be created 4096
# The created key must be protected by the passphrase betty

private_key="school"
bits=4096
passphrase="betty"

ssh-keygen -b $bits -N $passphrase -f $private_key
